### PR TITLE
feat: switch to node 18 and pkg

### PR DESCRIPTION
**Pull request by OmgImAlexis**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202637259445417

### CODE REVIEW

**Comment by elibosley** [comment]
Works great - I'm going to merge for this next release!

**Comment by OmgImAlexis** [comment]
Should be good to merge. 👍

**Comment by OmgImAlexis** [comment]
Only issue is the KA packets aren't being sent but that's handle that in a new branch after this is merged.

Looks like the cron isn't being called?
Running this I can confirm in the logs I see no KA packets. In the version before this KA packets are sent every 30s.

```
LOG_MOTHERSHIP_MESSAGES=true LOG_TYPE=pretty LOG_LEVEL=trace unraid-api start --debug
```

```
 tail -f /var/log/unraid-api/relay-outgoing-messages.log
 ```

**Comment by OmgImAlexis** [comment]
I could be wrong but I believe this diff may fix it as I think `Cron.Start` is needed, no?

```diff
diff --git a/src/mothership/jobs/cloud-connection-check-jobs.ts b/src/mothership/jobs/cloud-connection-check-jobs.ts
index 55eb960..6b2a453 100644
--- a/src/mothership/jobs/cloud-connection-check-jobs.ts
+++ b/src/mothership/jobs/cloud-connection-check-jobs.ts
@@ -4,18 +4,14 @@ import { mothershipLogger } from '@app/core';
 import { Cron, Expression, Initializer } from '@reflet/cron';
 import { cloudConnector } from '../cloud-connector';
 
+@Cron.Start
+@Cron.PreventOverlap
 export class MothershipJobs extends Initializer<typeof MothershipJobs> {
-
-	constructor() {
-		super();
-	}
-
 	@Cron(Expression.EVERY_5_MINUTES)
 	async logMessage() {
 		mothershipLogger.trace('MothershipJobs Is Still Running (Repeats every 5 minutes)');
 	}
 
-	@Cron.PreventOverlap
 	@Cron(Expression.EVERY_10_SECONDS)
 	async checkCloudConnection() {
 		try {
@@ -25,4 +21,3 @@ export class MothershipJobs extends Initializer<typeof MothershipJobs> {
 		}
 	}
 }
-
diff --git a/src/mothership/jobs/relay-keep-alive-jobs.ts b/src/mothership/jobs/relay-keep-alive-jobs.ts
index 09e2a59..eb44370 100644
--- a/src/mothership/jobs/relay-keep-alive-jobs.ts
+++ b/src/mothership/jobs/relay-keep-alive-jobs.ts
@@ -5,13 +5,9 @@ import { Cron, CurrentJob, Expression, Initializer, Job } from '@reflet/cron';
 import { sendMessage } from '@app/mothership/send-message';
 import { relayStore } from '@app/mothership/store';
 
+@Cron.Start
+@Cron.PreventOverlap
 export class RelayKeepAlive extends Initializer<typeof RelayKeepAlive> {
-
-	constructor() {
-		super();
-	}
-
-	@Cron.PreventOverlap
 	@Cron(Expression.EVERY_30_SECONDS)
 	async sendKeepAlive(@CurrentJob runningKeepAliveJob: Job) {
 		try {
@@ -27,4 +23,3 @@ export class RelayKeepAlive extends Initializer<typeof RelayKeepAlive> {
 		}
 	}
 }
-

```

**Comment by elibosley** [comment]
> I could be wrong but I believe this diff may fix it as I think `Cron.Start` is needed, no?
> 
> ```diff
> diff --git a/src/mothership/jobs/cloud-connection-check-jobs.ts b/src/mothership/jobs/cloud-connection-check-jobs.ts
> index 55eb960..6b2a453 100644
> --- a/src/mothership/jobs/cloud-connection-check-jobs.ts
> +++ b/src/mothership/jobs/cloud-connection-check-jobs.ts
> @@ -4,18 +4,14 @@ import { mothershipLogger } from '@app/core';
>  import { Cron, Expression, Initializer } from '@reflet/cron';
>  import { cloudConnector } from '../cloud-connector';
>  
> +@Cron.Start
> +@Cron.PreventOverlap
>  export class MothershipJobs extends Initializer<typeof MothershipJobs> {
> -
> -	constructor() {
> -		super();
> -	}
> -
>  	@Cron(Expression.EVERY_5_MINUTES)
>  	async logMessage() {
>  		mothershipLogger.trace('MothershipJobs Is Still Running (Repeats every 5 minutes)');
>  	}
>  
> -	@Cron.PreventOverlap
>  	@Cron(Expression.EVERY_10_SECONDS)
>  	async checkCloudConnection() {
>  		try {
> @@ -25,4 +21,3 @@ export class MothershipJobs extends Initializer<typeof MothershipJobs> {
>  		}
>  	}
>  }
> -
> diff --git a/src/mothership/jobs/relay-keep-alive-jobs.ts b/src/mothership/jobs/relay-keep-alive-jobs.ts
> index 09e2a59..eb44370 100644
> --- a/src/mothership/jobs/relay-keep-alive-jobs.ts
> +++ b/src/mothership/jobs/relay-keep-alive-jobs.ts
> @@ -5,13 +5,9 @@ import { Cron, CurrentJob, Expression, Initializer, Job } from '@reflet/cron';
>  import { sendMessage } from '@app/mothership/send-message';
>  import { relayStore } from '@app/mothership/store';
>  
> +@Cron.Start
> +@Cron.PreventOverlap
>  export class RelayKeepAlive extends Initializer<typeof RelayKeepAlive> {
> -
> -	constructor() {
> -		super();
> -	}
> -
> -	@Cron.PreventOverlap
>  	@Cron(Expression.EVERY_30_SECONDS)
>  	async sendKeepAlive(@CurrentJob runningKeepAliveJob: Job) {
>  		try {
> @@ -27,4 +23,3 @@ export class RelayKeepAlive extends Initializer<typeof RelayKeepAlive> {
>  		}
>  	}
>  }
> -
> ```

Excellent point. Changed relay to have the start function for reflet/cron and also changed the dashboard to use a cron job instead of an interval which should make things easier to track.

**Pull request merged**
